### ISSUE TITLE
This mod will cause the bot not to move

### ISSUE THREAD

**Issue by OrangeMiracle** [m-barneto/BossNotifier#3]
My AKI server is version 3.8.
When I install this mod on the client, it displays notifications normally based on boss spawning, but causes all bots to just stand still and not shoot. Other than that everything functions normally. I have eliminated all mod conflict issues, which means that even if I install this mod separately, the bot will not move.

**Comment by m-barneto** [comment]
Could you test without the mod as well? I'm noticing this in base 3.8 on my end and thought it was weird.
